name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  HUSKY: "0"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.gitea/actions/setup

      - name: Check formatting
        run: pnpm format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.gitea/actions/setup

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.gitea/actions/setup

      - name: Generate code
        run: pnpm generate:ci

      - name: Type check
        run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.gitea/actions/setup

      - name: Generate code
        run: pnpm generate:ci

      - name: Build server
        run: pnpm build:server

      - name: Build client
        run: pnpm build:client

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.gitea/actions/setup

      - name: Generate code
        run: pnpm generate:ci

      - name: Run server unit tests
        run: pnpm --filter @createrington/server test:unit
