import config from "@/config";
import { EmbedColors } from "../../colors";
import { createEmbed } from "../../embed-builder";
import { Discord } from "@/discord/constants";

export const TicketEmbedPresets = {
  /**
   * Creates a Ticket panel embed
   */
  panel() {
    const embed = createEmbed()
      .title("🎟️ Support Ticket")
      .description(
        "To create a ticket, click the **Create Ticket** button below.",
      )
      .color(EmbedColors.Info)
      .fields([
        {
          name: "Need help?",
          value: "Click the button below to open a private support thread.",
        },
        {
          name: " ",
          value: `[${config.meta.name}](${config.meta.links.website})`,
        },
      ]);

    return embed;
  },

  /**
   * Creates a Ticket welcome embed
   */
  welcome(userId: string, minecraftUsername: string) {
    const embed = createEmbed()
      .description(
        `👋 Welcome ${Discord.Users.mention(
          userId,
        )} (Minecraft: **${minecraftUsername}**)
            \nPlease describe your issue in detail and include any screenshots or videos.
            \n Support will be with you shortly ${Discord.Roles.mention(
              Discord.Roles.ADMIN,
            )}
            \nTo close this ticket, press the **Close** button below.
            `,
      )
      .color(EmbedColors.Info)
      .field(" ", `[${config.meta.name}](${config.meta.links.website})`)
      .timestamp();

    return embed;
  },

  /**
   * Creates a Ticket closure embed
   */
  close(closedBy: string) {
    const embed = createEmbed()
      .title("🔒 Ticket Closed")
      .description(
        `This ticket has been closed by ${Discord.Users.mention(
          closedBy,
        )}.\n\n` +
          `The channel will remain open for review. Use the buttons below if you need to reopen or delete`,
      )
      .color(EmbedColors.Error)
      .timestamp();

    return embed;
  },

  /**
   * Creates a Ticket reopened embed
   */
  reopen(reopenedBy: string, creatorDiscordId: string) {
    return createEmbed()
      .title("🔓 Ticket Reopened")
      .description(
        `This ticket has been reopened by ${Discord.Users.mention(reopenedBy)}.\n\n` +
          `${Discord.Users.mention(creatorDiscordId)} can now send messages again.`,
      )
      .color(EmbedColors.Success)
      .timestamp();
  },

  /**
   * Creates a Ticket transcript embed
   */
  transcript(data: {
    ticketNumber: number;
    type: string;
    creatorDiscordId: string;
    closedByDiscordId: string;
    generatedBy: string;
    channelId: string;
    createdAt: Date;
    closedAt: Date | null;
  }) {
    return createEmbed()
      .title(`📄 Ticket #${data.ticketNumber} Transcript`)
      .description(
        `**Ticket Type:** ${data.type}\n` +
          `**Creator:** ${Discord.Users.mention(data.creatorDiscordId)}\n` +
          `**Closed By:** ${Discord.Users.mention(data.closedByDiscordId)}\n` +
          `**Generated By:** ${Discord.Users.mention(data.generatedBy)}\n` +
          `**Channel:** <#${data.channelId}>`,
      )
      .color(EmbedColors.Info)
      .fields([
        {
          name: "Created At",
          value: `<t:${Math.floor(data.createdAt.getTime() / 1000)}:F>`,
          inline: true,
        },
        {
          name: "Closed At",
          value: data.closedAt
            ? `<t:${Math.floor(data.closedAt.getTime() / 1000)}:F>`
            : "N/A",
          inline: true,
        },
      ])
      .timestamp();
  },
};
