// Optional per-route text overrides for the og-html variants generated by
// build-dist.js. Routes are keyed by pathname and matched against the card
// images in packages/client/public/assets/og/ (filename = route). A route
// without an entry still gets its image and URL tags swapped; title,
// description, and image alt fall back to the global ones in index.html.
export const OG_ROUTES = {
  "/structure-packs": {
    title: "Shape the next world.",
    description:
      "Mining dimensions rotate on a schedule. Boost the themed dimension you want next and weighted voting decides what appears through the portal.",
    imageAlt:
      "The Createrington team gathered at a glowing Parallel Worlds portal.",
  },
};
